### ISSUE TITLE
Upgrade name.

### ISSUE THREAD

**Issue by cagdasoztekin** [hantuzun/resume#1]
Change line:
[github.com/emrehan/resume/blob/master/resume.pdf](https://github.com/emrehan/resume/blob/master/resume.pdf)

=>

[github.com/hantuzun/resume/blob/master/resume.pdf](https://github.com/hantuzun/resume/blob/master/resume.pdf)

**Comment by hantuzun** [comment]
will do

**Comment by hantuzun** [comment]
Closed by #2
